# Generated by Django 6.0 on 2025-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. Deep Learning, Web Dev", max_length=100
                    ),
                ),
                (
                    "category_css_class",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty for Pink. Type 'tech-web' for Cyan.",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("published_at", models.DateField()),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link to full article (optional)",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
