# Generated by Django 6.0 on 2025-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name (e.g. my-first-post)",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
