# Generated by Django 6.0 on 2026-02-02 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_codeexecution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeexecution",
            old_name="code_input",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="codeexecution",
            old_name="created_at",
            new_name="executed_at",
        ),
        migrations.RenameField(
            model_name="codeexecution",
            old_name="code_output",
            new_name="output",
        ),
        migrations.AlterField(
            model_name="codeexecution",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
