# Generated by Django 6.0 on 2026-02-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0006_rename_code_input_codeexecution_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeexecution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
