# Generated by Django 6.0 on 2026-02-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0007_alter_codeexecution_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeexecution",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
