# Generated by Django 6.0 on 2026-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0008_codeexecution_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeexecution",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="codeexecution",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
