# Generated by Django 6.0 on 2026-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0009_codeexecution_city_codeexecution_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeexecution",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
