# Generated by Django 6.0 on 2026-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0010_codeexecution_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or FontAwesome class (e.g., 🧠 or 'fas fa-brain')",
                        max_length=50,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link for the 'Learn More' button",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in which it appears on the page"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
