# Generated by Django 6.0 on 2026-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0011_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Cognilume", help_text="Main heading", max_length=100
                    ),
                ),
                ("subtitle", models.TextField()),
                (
                    "primary_btn_text",
                    models.CharField(default="Sign up for Cognilume", max_length=50),
                ),
                (
                    "primary_btn_link",
                    models.CharField(default="/register/", max_length=200),
                ),
                (
                    "secondary_btn_text",
                    models.CharField(default="Try AI Tutor free", max_length=50),
                ),
                (
                    "secondary_btn_link",
                    models.CharField(default="/ai-tutor/", max_length=200),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your brain image here",
                        null=True,
                        upload_to="hero_images/",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(default="Cognilume Intelligence", max_length=100),
                ),
            ],
            options={
                "verbose_name_plural": "Home Page Content",
            },
        ),
    ]
