# Generated by Django 6.0 on 2026-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0012_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload your brain image here",
                null=True,
                upload_to="Image/",
            ),
        ),
    ]
