# Generated by Django 6.0 on 2026-06-18 12:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0013_alter_homepage_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload your brain image here",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/Image/",
                    location="E:\\Code\\PragyaPythonProject\\ImageWebsite\\HtmlWebsite\\Image",
                ),
                upload_to="",
            ),
        ),
    ]
