# Generated by Django 6.0 on 2026-06-18 12:40

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0015_alter_homepage_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload your brain image here",
                null=True,
                storage=first_app.models.OverwriteStorage(
                    base_url="/Image/",
                    location="E:\\Code\\PragyaPythonProject\\ImageWebsite\\HtmlWebsite\\Image",
                ),
                upload_to="Home/",
            ),
        ),
    ]
