# Generated by Django 6.0 on 2026-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0016_alter_homepage_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="services_heading_highlight",
            field=models.CharField(
                blank=True, default="Smarter Tomorrow", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_heading_main",
            field=models.CharField(
                blank=True, default="Intelligent Solutions for a", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_label",
            field=models.CharField(blank=True, default="WHAT WE DO", max_length=50),
        ),
    ]
