# Generated by Django 6.0 on 2026-06-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0017_homepage_services_heading_highlight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="home_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="first_app.homepage",
            ),
        ),
    ]
