# Generated by Django 6.0 on 2026-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0018_service_home_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Link for the 'Learn More' button",
                max_length=200,
                null=True,
            ),
        ),
    ]
