# Generated by Django 6.0 on 2026-06-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0021_classgroup_periodtime_teacher_timetableentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "subject_table",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AlterField(
            model_name="periodtime",
            name="period_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teachers", to="first_app.subject"
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="first_app.subject",
            ),
        ),
    ]
