# Generated by Django 6.0 on 2026-06-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0022_subject_remove_teacher_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Use this to sort days (e.g., Monday=1, Tuesday=2)",
                    ),
                ),
            ],
            options={
                "db_table": "day_of_week_table",
                "ordering": ["order"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="days",
            field=models.ManyToManyField(
                related_name="timetable_entries", to="first_app.dayofweek"
            ),
        ),
        migrations.RemoveField(
            model_name="timetableentry",
            name="day",
        ),
    ]
