# Generated by Django 6.0 on 2026-07-07 21:00

import django.db.models.deletion
import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0023_dayofweek_alter_timetableentry_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your logo image here",
                        null=True,
                        storage=first_app.models.OverwriteStorage(
                            base_url="/Image/",
                            location="E:\\Code\\PragyaPythonProject\\ImageWebsite\\HtmlWebsite\\Image",
                        ),
                        upload_to="Home/Technology",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in which they appear"
                    ),
                ),
                (
                    "home_page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="first_app.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["order"],
            },
        ),
    ]
